import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function seriesSeeder() {
    await prisma.series.createMany({
        data: [
            {
                id: 'df65b3a7-c9d9-4cb0-a9e2-a50ed189e464',
                title: 'Zaginione Światło',
                description: 'Intrygujący serial o grupie badaczy, którzy podróżują po całym świecie, odkrywając starożytne tajemnice i zaginione cywilizacje.',
                actors: ["aleksandra kowalska", "piotr nowak", "magdalena wiśniewska"],
                creators: ["krzysztof kowal", "anna zalewska"],
                categories: ["Dokumentalne", "Przygodowe"],
                seasons: 3,
                year: 2021,
                thumbnailUrl: 'zaginione-swiatlo.jpg',
                trailerUrl: 'zaginione-swiatlo.mp4'
            },
            {
                id: '5651f11f-5079-4499-9fa7-01ebca77c679',
                title: 'Przestrzeń Nieskończona',
                description: 'W odległej przyszłości załoga statku kosmicznego "Aurora" wyrusza w epicką podróż przez galaktyki, odkrywając nieznane planety, obce cywilizacje i tajemnicze zjawiska kosmiczne.',
                actors: ['emma carter', 'john mercer', 'aisha khan', 'alex chang'],
                creators: ['olivia reynolds', 'michael turner'],
                categories: ['Science Fiction', 'Przygodowe'],
                seasons: 1,
                year: 2018,
                thumbnailUrl: 'przestrzen-nieskonczona.jpg',
                trailerUrl: 'przestrzen-nieskonczona.mp4',
            },
            {
                id: '63c83aad-56fe-4494-9139-2a3ac695097e',
                title: 'Mroczne Zagadki',
                description: 'Detektyw Julia Miller, znana ze swojego bystrzego umysłu i zdolności do rozwiązywania najbardziej skomplikowanych zagadek kryminalnych, bierze udział w śledztwach, które prowadzą ją do mrocznych tajemnic i zjawisk paranormalnych.',
                warnings: ['16+', 'Alkohol', 'Przemoc', 'Przestępstwo'],
                actors: ['anna gomez', 'james harris', 'emma clarke', 'david walker'],
                creators: ['martin evans', 'sarah williams'],
                categories: ['Kryminał', 'Paranormalne'],
                seasons: 2,
                year: 2022,
                thumbnailUrl: 'mroczne-zagadki.png',
                trailerUrl: 'mroczne-zagadki.mp4',
            },
            {
                id: '38cd2d1d-ba22-44a3-a922-c820d99e945c',
                title: 'Złoty Cień',
                description: 'Detektyw Marek Kowalski, doświadczony śledczy, wraca do pracy, aby rozwiązać serię tajemniczych zbrodni, które zdają się być powiązane z cieniem przeszłości miasta.',
                warnings: ['16+', 'Przekleństwa', 'Seks', 'Alkohol', 'Przemoc'],
                actors: ['grzegorz damiecki', 'agnieszka więdłocha', 'tomasz karolak', 'magdalena różczka'],
                creators: ['katarzyna nowak', 'piotr majewski'],
                categories: ['Kryminał', 'Dramat'],
                seasons: 2,
                year: 2021,
                thumbnailUrl: 'zloty-cien.jpg',
                trailerUrl: 'zloty-cien.mp4',
            },
            {
                id: 'ad1b96b2-d4ce-4f37-a61b-3f40977971e7',
                title: 'Miłość na Mazurach',
                description: 'W malowniczej miejscowości na Mazurach, gdzie jeziora i lasy tworzą idealne tło, mieszkańcy przeżywają historie miłości, przyjaźni i rodzinne sekrety.',
                actors: ['agnieszka dygant', 'tomasz kot', 'maria peszek', 'borys szyc'],
                creators: ['piotr kwiatkowski', 'marta szymańska'],
                categories: ["Romans", "Obyczajowe"],
                seasons: 3,
                year: 2020,
                thumbnailUrl: 'milosc-na-mazurach.jpg',
                trailerUrl: 'milosc-na-mazurach.mp4',
            },
            {
                id: '8fa4b473-336c-40cd-92f0-9f002eee1aab',
                title: 'Złodziej Czasu',
                description: 'W małym miasteczku, gdzie czas zdaje się mijać inaczej, tajemniczy złodziej zaczyna kradzież czasu, wprowadzając bohaterów w wir niewyjaśnionych zdarzeń.',
                actors: ['piotr adamczyk', 'joanna kulig', 'jerzy stuhr', 'ewa frąckiewicz'],
                creators: ['magdalena kowalska', 'jan nowak'],
                categories: ['Kryminał', 'Science Fiction'],
                seasons: 2,
                year: 2022,
                thumbnailUrl: 'zlodziej-czasu.jpg',
                trailerUrl: 'zlodziej-czasu.mp4',
            },
            {
                id: '6106adf3-20f6-4efc-8534-c981952cf364',
                title: 'Śmiechoterapia',
                description: 'Grupa ludzi o różnych troskach i problemach decyduje się na nietypową terapię, gdzie głównym narzędziem jest śmiech. Razem odkrywają, że czasem najlepszym lekarstwem na życiowe zawirowania jest dobra dawka humoru.',
                actors: ['małgorzata kożuchowska', 'bolek polívka', 'katarzyna figura', 'cezary pazura'],
                creators: ['krzysztof ziębiński', 'agnieszka kowalska'],
                categories: ['Komedia', 'Obyczajowe'],
                seasons: 2,
                year: 2023,
                thumbnailUrl: 'smiechoterapia.jpg',
                trailerUrl: 'smiechoterapia.mp4',
            },
            {
                id: '893ccb72-40ea-477f-82ac-5e9a98b92a11',
                title: 'Bezpieczna Przystań',
                description: 'Grupa ludzi z różnymi bagażami życiowymi znajduje schronienie w tajemniczym schronisku, gdzie każdy z nich ukrywa własne tajemnice. Razem próbują odbudować swoje życie i znaleźć bezpieczną przystań przed przeszłością.',
                actors: ['agata kulesza', 'maciej stuhr', 'małgorzata foremniak', 'andrzej chyra'],
                creators: ['magdalena zięba', 'tomasz kowalski'],
                categories: ['Dramat', 'Psychologiczne'],
                seasons: 2,
                year: 2017,
                thumbnailUrl: 'bezpieczna-przystan.jpg',
                trailerUrl: 'bezpieczna-przystan.mp4',
            },
            {
                id: '8c3acd79-361f-49b9-bd5d-f75a25629905',
                title: 'Eteryczny Labirynt',
                description: 'Grupa naukowców odkrywa tajemniczy portal do innego wymiaru, gdzie reguły czasu, przestrzeni i rzeczywistości ulegają zmianie. Bohaterowie muszą zrozumieć, co się stało, zanim zostaną uwięzieni w eterycznym labiryncie na zawsze.',
                actors: ['janusz gajos', 'olga bołądź', 'paweł deląg', 'magdalena popławska'],
                creators: ['krzysztof wójcik', 'kamil nowak'],
                categories: ['Science Fiction', 'Fantasy'],
                seasons: 3,
                year: 2019,
                thumbnailUrl: 'eteryczny-labirynt.jpg',
                trailerUrl: 'eteryczny-labirynt.mp4',
            },
            {
                id: '447b979d-34dc-4e30-ac35-a37273ae90a0',
                title: 'Złamane Prawo',
                description: 'Detektyw Kamil Zawadzki, znany ze swojego niekonwencjonalnego podejścia, stawia czoło zbrodniom i korupcji, często przekraczając granice prawa. Jego działania prowadzą do napięć w środowisku policyjnym i społecznym.',
                actors: ['andrzej seweryn', 'małgorzata kożuchowska', 'borys szyc', 'agnieszka więdłocha'],
                creators: ['katarzyna nowak', 'michał kowalski'],
                categories: ['Kryminał', 'Dramat'],
                seasons: 2,
                year: 2015,
                thumbnailUrl: 'zlamane-prawo.jpg',
                trailerUrl: 'zlamane-prawo.mp4',
            }
        ]
    })
}

export default seriesSeeder;